"""Add AuthUsers model for authentication

Revision ID: eb55377110e8
Revises: 
Create Date: 2025-07-04 13:19:47.307897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb55377110e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clients_email', table_name='clients')
    op.drop_index('idx_clients_last_action', table_name='clients')
    op.drop_index('idx_websites_domain', table_name='websites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_websites_domain', 'websites', ['domain_name'], unique=False)
    op.create_index('idx_clients_last_action', 'clients', ['last_action'], unique=False)
    op.create_index('idx_clients_email', 'clients', ['email'], unique=False)
    # ### end Alembic commands ### 